def add_model_config(parser):
    parser.add_argument('--model_name', help='gnn model', type=str, default="s2diconv")
    parser.add_argument('--num_layers', help='number of gnn layers', type=int, default=3)
    parser.add_argument('--dropout', help='drop out of gnn model', type=float, default=0.5)
    parser.add_argument('--hidden_dim', help='hidden units', type=int, default=64)
    parser.add_argument('--edge_dim', help='hidden units of linearR model in edge-level tasks', type=int, default=2)
    parser.add_argument('--prop_steps', help='prop steps', type=int, default=4)
    parser.add_argument('--r', help='symmetric normalized unit', type=float, default=0.5)
    parser.add_argument('--node_q', help='the imaginary part of the complex unit in node-level tasks', type=float, default=0.035)
    parser.add_argument('--edge_q', help='the imaginary part of the complex unit in edge-level tasks', type=float, default=0.056)
    parser.add_argument('--neighbor_hops', help='number of hops to consider', type=int, default=5)
    parser.add_argument('--filter_order', help='order of filter process', type=int, default=10)
    parser.add_argument('--nste_alpha', help='propagation coefficient of nste', type=float, default=0.4)
    parser.add_argument('--nste_beta', help='propagation coefficient of nste', type=float, default=0.2)
